### ISSUE TITLE
Creating links/workflows that shows on all articles is difficult

### ISSUE THREAD

**Issue by HeliSark** [the-stencil-io/the-stencil-composer#29]
**User case:** There are some links or workflows that needs to be added to all articles. The only way to do it now is to tab all the boxes in the locations. 

**Suggestion:** Add box "Add to all articles" so I can just click that, instead of clicking all of the separate articles in the list.

**Comment by jocelynmutso** [comment]
Option to add a link or a workflow to all articles has been added to

1. Link Composer dialog
2. Link Edit dialog
3. Workflow Composer dialog
4. Workflow Edit dialog

Upon clicking the "all articles" button, all the articles are selected, and "de-select all articles" removes all articles simultaneously. 

**NOTE**: Once you click "all articles", any previous article associations are lost. If you want to add the link / workflow back to only certain, individual articles, you will need to manually go back through the articles one-by-one to add them back.
