### ISSUE TITLE
Pages could have a text template

### ISSUE THREAD

**Issue by HeliSark** [the-stencil-io/the-stencil-composer#30]
**User case:** The pages usually follow similar template. Now I need to copy/paste the text from other pages when I'm creating a new page.

**Suggestion:** It would be great if I could create template for the pages so when I create new page, it could already show the basic elements and markdowns on the page. Then I would just need to fix the texts.

**Comment by jocelynmutso** [comment]
Templates Card has been added to Dashboard (now called "Activities". Implementation to come soon.

**Comment by jocelynmutso** [comment]
Templates feature now added.

Templates can be created, edited, viewed, and deleted.  

A Template can be applied to a new page upon creation of that page.
