### ISSUE TITLE
Filter options for adding workflows or links

### ISSUE THREAD

**Issue by HeliSark** [the-stencil-io/the-stencil-composer#32]
**User case:** When I'm adding a new workflow to the article, the list is very long. I usually remember the name of the workflow or parts of it so I want to search or filter the workflows by name. Either the technical name or the localized name.

**Suggestion:** Add search option or filter option to the names so I can find easily the correct workflow by it's name.

**Comment by jocelynmutso** [comment]
The new Stencil version now contains filtering for links and workflows. This filtering is done via search.  This search filter can be found both in Links / Workflows edit, but also in the Search feature of the toolbar.

---

Workflows and links editing tab now contains three parts: 

TOP: A section at the top shows you the workflows/links associated with this article currently.
MIDDLE: A search box for searching ALL site workflows/links.
BOTTOM: A list of ALL workflows/links. The search box filters out these items as your search gets more specific.

Once you've found what you're looking for, you can click an "add" icon to add it to the TOP section of the view. Then, you can "Apply changes". 

--- These changes will be applied in new version.
