### ISSUE TITLE
sorting functionality to release main view

### ISSUE THREAD

**Issue by Tatuk** [the-stencil-io/the-stencil-composer#60]
<img width="1239" alt="Screenshot 2022-09-26 at 14 38 56" src="https://user-images.githubusercontent.com/24618519/192267698-708ca73e-3a8e-405e-a06b-1435f8efd58e.png">

Columns; Tag and Created should be sortable + Created time stamp should more readable format like dd-mm-yyyy hh:mm

**Comment by jocelynmutso** [comment]
ReleasesView
 
- Add react-burger date formatting component
- Add sort functionality which should work in the same way as in hdes-composer
